name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag git.skill17.com/${{ github.repository }}

      - name: Login at Registry
        run: echo "${{ secrets.PASSWORD }}" | docker login git.skill17.com -u ${{ secrets.USER }} --password-stdin

      - name: Push to Registry
        run: docker push git.skill17.com/${{ github.repository }}